### ISSUE TITLE
Crash Assistant modlist feature is not configured properly.

### ISSUE THREAD

**Issue by KostromDan** [FTBTeam/FTB-Modpack-Issues#8029]
### Modpack

FTB Skies 2

### Modpack version

1.0.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

```toml
[modpack_modlist]
	#nicknames of players, who considered as modpack creator.
	#Only this players can overwrite modlist.json
	#If this feature is enabled and this array is empty, will be appended with nickname of current player.
	modpack_creators = ["FTB Team"]

	#If enabled, modlist.json will be overwritten on every launch(first tick of TitleScreen),
	#then game is launched by modpack creator.
	#So you won't forget to save it before publishing.
	#If you want to save manually: disable this and use '/crash_assistant modlist save' command.
	auto_update = true
```

It should contain the actual nicknames of the people releasing the modpack.
These names are not displayed anywhere — they are just a technical parameter used to identify the modpack creators and to overwrite modlist.json on launch.
This is needed to track which changes were made by the end user.

Since the actual creators' names are missing, modlist.json is very outdated and shows the default modpack as if it was modified.

![Image](https://github.com/user-attachments/assets/1e55a231-d693-4236-b6d8-290aeb1d49ea)

### Steps to reproduce

-

### Expected behaviour

-

**Comment by KostromDan** [comment]
Also since crashes are reported not only to the discord, but also github, I would recommend to disable this option:
```toml
[generated_message]
	#Color modified mods count/analysis in msg with ANSI.
	#Can be needed to be disabled if issues are reported to something not supporting ANSI codeblocks, like GitHub.
	color_message = true
``` 
Because Github doesn't support ANSI and it's looks bad.
